stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: ""
  SONAR_HOST_URL: "http://192.168.10.194:9000"
  SONAR_SCANNER_OPTS: >
    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
    -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json
    -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
    -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $HOME/.m2/repository

image: maven:3.8.1-openjdk-17

#  Build
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  tags:
    - theportal

#  Unit Tests + JaCoCo
unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test jacoco:report
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/site/jacoco/jacoco.xml
    when: always
  tags:
    - theportal

# SCA
sca_owasp:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS org.owasp:dependency-check-maven:check -Pdependency-check -Dformat=ALL -DoutputDirectory=target
  artifacts:
    paths:
      - target/dependency-check-report.xml
      - target/dependency-check-report.html
      - target/dependency-check-report.json

    when: always
  tags:
    - theportal

# SonarQube Analysis (depends on both tests + SCA)
sonarqube_analysis:
  stage: test
  script:
    - mvn compile
    - >
      mvn sonar:sonar
      -Dsonar.projectKey=callcenter-service
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      $SONAR_SCANNER_OPTS
  needs:
    - job: unit_tests
    - job: sca_owasp
  tags:
    - theportal
