/*package com.example.callcenter.Entity;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface ReportRepository extends JpaRepository<Report, Long> {

    // Find the latest report for a request
    Optional<Report> findFirstByRequest_IdROrderByGeneratedDateDesc(Long requestId);

    // Find all reports for a request (for history)
    List<Report> findByRequest_IdR(Long requestId);

    // Find reports by status
    List<Report> findByStatus(ReportStatus status);

    // Check if a request has a report with specific status
    boolean existsByRequest_IdRAndStatus(Long requestId, ReportStatus status);

    // Find reports generated by a specific agent

    // Find reports pending approval
    List<Report> findByStatusOrderByGeneratedDateDesc(ReportStatus status);

    // Find reports by date range
    @Query("SELECT r FROM Report r WHERE r.generatedDate BETWEEN :startDate AND :endDate")
    List<Report> findByDateRange(@Param("startDate") LocalDateTime startDate,
                                 @Param("endDate") LocalDateTime endDate);

    // Find reports by request type
    List<Report> findByRequestType(RequestType requestType);

    // Find reports that need attention (pending approval or rejected)
    @Query("SELECT r FROM Report r WHERE r.status IN ('PENDING_APPROVAL', 'REJECTED')")
    List<Report> findReportsNeedingAttention();

    // Count reports by status
    long countByStatus(ReportStatus status);

    // Find reports with contact rate above threshold
    @Query("SELECT r FROM Report r WHERE r.contactRate > :threshold")
    List<Report> findByContactRateAbove(@Param("threshold") double threshold);
}*/